---
apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-migrate
  annotations:
    description: sentry db migrations
spec:
  activeDeadlineSeconds: 60
  template:
    spec:
      imagePullSecrets:
        - name: ev-images
      restartPolicy: Never
      containers:
        - name: sentry-onpremise
          image: registry.eventador.io/dev/sentry-onpremise:latest
          command:
            - /entrypoint.sh
            - upgrade
          env:
          - name: SENTRY_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sentrysecrets
                key: secretKey
          - name: SENTRY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: sentrysecrets
                key: dbName
          - name: SENTRY_DB_USER
            valueFrom:
              secretKeyRef:
                name: sentrysecrets
                key: dbUser
          - name: SENTRY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sentrysecrets
                key: dbPassword
          - name: SENTRY_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: sentrysecrets
                key: dbHost
          - name: SENTRY_POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: sentrysecrets
                key: dbPort
          - name: SENTRY_REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: sentrysecrets
                key: redisHost
          - name: SENTRY_USE_SSL
            value: "1"
          - name: SENTRY_WEB_PORT
            value: "8000"
          - name: SENTRY_WEB_WORKERS
            value: "3"
